--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-06-19 14:12:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16631)
-- Name: messages_contacts; Type: TABLE; Schema: public; Owner: cucutoche
--

CREATE TABLE public.messages_contacts (
    id integer NOT NULL,
    name character varying(100),
    email character varying(100),
    message text,
    state character varying(100)
);


ALTER TABLE public.messages_contacts OWNER TO cucutoche;

--
-- TOC entry 217 (class 1259 OID 16630)
-- Name: messages_contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: cucutoche
--

CREATE SEQUENCE public.messages_contacts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.messages_contacts_id_seq OWNER TO cucutoche;

--
-- TOC entry 4821 (class 0 OID 0)
-- Dependencies: 217
-- Name: messages_contacts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cucutoche
--

ALTER SEQUENCE public.messages_contacts_id_seq OWNED BY public.messages_contacts.id;


--
-- TOC entry 220 (class 1259 OID 16700)
-- Name: municipalities; Type: TABLE; Schema: public; Owner: cucutoche
--

CREATE TABLE public.municipalities (
    id integer NOT NULL,
    name text,
    subtitle text,
    information text,
    video text,
    image text,
    background text
);


ALTER TABLE public.municipalities OWNER TO cucutoche;

--
-- TOC entry 219 (class 1259 OID 16699)
-- Name: municipalities_id_seq; Type: SEQUENCE; Schema: public; Owner: cucutoche
--

CREATE SEQUENCE public.municipalities_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.municipalities_id_seq OWNER TO cucutoche;

--
-- TOC entry 4822 (class 0 OID 0)
-- Dependencies: 219
-- Name: municipalities_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cucutoche
--

ALTER SEQUENCE public.municipalities_id_seq OWNED BY public.municipalities.id;


--
-- TOC entry 222 (class 1259 OID 16712)
-- Name: places; Type: TABLE; Schema: public; Owner: cucutoche
--

CREATE TABLE public.places (
    id integer NOT NULL,
    municipality_id integer,
    name text,
    information text,
    video text,
    image text,
    background text
);


ALTER TABLE public.places OWNER TO cucutoche;

--
-- TOC entry 221 (class 1259 OID 16711)
-- Name: places_id_seq; Type: SEQUENCE; Schema: public; Owner: cucutoche
--

CREATE SEQUENCE public.places_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.places_id_seq OWNER TO cucutoche;

--
-- TOC entry 4823 (class 0 OID 0)
-- Dependencies: 221
-- Name: places_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cucutoche
--

ALTER SEQUENCE public.places_id_seq OWNED BY public.places.id;


--
-- TOC entry 4651 (class 2604 OID 16634)
-- Name: messages_contacts id; Type: DEFAULT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.messages_contacts ALTER COLUMN id SET DEFAULT nextval('public.messages_contacts_id_seq'::regclass);


--
-- TOC entry 4652 (class 2604 OID 16703)
-- Name: municipalities id; Type: DEFAULT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.municipalities ALTER COLUMN id SET DEFAULT nextval('public.municipalities_id_seq'::regclass);


--
-- TOC entry 4653 (class 2604 OID 16715)
-- Name: places id; Type: DEFAULT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.places ALTER COLUMN id SET DEFAULT nextval('public.places_id_seq'::regclass);


--
-- TOC entry 4811 (class 0 OID 16631)
-- Dependencies: 218
-- Data for Name: messages_contacts; Type: TABLE DATA; Schema: public; Owner: cucutoche
--

COPY public.messages_contacts (id, name, email, message, state) FROM stdin;
1	omar salas	ogsalas@fesc.edu.co	esta es una prueba	Envio exitoso
2	omar	moteros1.0@fesc.edu.co	asasasa	Envio exitoso
3	SAN MATEO	123@fesc.edu.co	adaaa	Envio exitoso
4	mateo	mateo@gmail.com	sfsdsdsdas	Envio exitoso
5	mateo	mateo@gmail.com	esta es una prueba	Envio exitoso
6	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
7	Gabriel Alvarez Maldonado	gabriel@gmail.com	asasasa	Envio exitoso
8	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
9	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
10	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio fallido
11	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
12	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
13	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
14	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
15	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
16	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
17	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
18	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
19	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
20	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
21	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
22	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
23	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
24	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
25	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
26	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
27	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
28	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
29	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
30	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
31	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
32	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
33	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
34	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
35	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
36	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
37	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
38	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
39	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
40	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
41	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
42	pepito perez	pepitoperez@gmail.con	omar salas	Envio exitoso
43	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
44	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio exitoso
45	Gabriel Alvarez Maldonado	gabriel@gmail.com	Donde puedo conseguir los sitios turisticos de pamplona, ayuda por favor	Envio fallido
46	Gabriel Alvarez Maldonado	gabriel@gmail.com	omar salas	Envio exitoso
\.


--
-- TOC entry 4813 (class 0 OID 16700)
-- Dependencies: 220
-- Data for Name: municipalities; Type: TABLE DATA; Schema: public; Owner: cucutoche
--

COPY public.municipalities (id, name, subtitle, information, video, image, background) FROM stdin;
1	ARBOLEDAS	La Fabrica de Agua de Norte de Santander\n	El Bello Municipio de Arboledas “La Fábrica de agua”, fue fundada el 24 de marzo de 1550 por Juan de Cuellar El nombre de este Municipio se debe a " La Arboleda" que rodea la planicie.\n\nArboledas Localizada a 82 km aproximadamente a 3 horas de Cúcuta, temperatura media de 22°C y una altitud de 946 metros sobre el nivel del mar, es pionero en el Aviturismo \n\nCada vez que vayas a algún lugar mágico, pide permiso para entrar, ya que la naturaleza te escucha, ve con la mejor vibra positiva y disfruta, admira y respeta lo que nos ofrece nuestro planeta\n	\N	/static/municipalitie/ARBOLEDAS/image.jpg	/static/municipalitie/ARBOLEDAS/background.jpg
2	BOCHALEMA	"El Paraíso Turístico de Norte de Santander"	Bochalema es un municipio colombiano ubicado en el departamento de Norte de Santander. Su cabecera municipal dista a 45 km de Cúcuta, capital del departamento.\n\nBochalema fue el nombre del valle habitado por las tribus indígenas de los Catires, Chiracocas y Bocalemas, quienes habían asentado allí sus comunidades pues se encontraban atraídos por la cantidad de agua que corría por su ladera y por su buen clima.\n\nFué fundado en 1759, por el español Juan José Villamizar. En 1826, fue erigido como municipio, y en 1872 parroquia, siendo guía espiritual el sacerdote Ramón García, nativo de la localidad. Uno de los personajes más representativos es el poeta Eduardo Vélez Contreras reconocido por haber creado los símbolos emblemáticos de este municipio y también por haber sido amigo y colega del compositor y director José Rozo Contreras.\n\nSu privilegiada ubicación geográfica, su historia rica en cultura y tradiciones, así como la belleza de sus paisajes, hacen de este lugar un destino imperdible para aquellos que buscan descubrir la belleza del norte del país. Con una población acogedora y vibrante, Bochalema ofrece a sus visitantes una experiencia única, donde podrán sumergirse en sus festividades, degustar su deliciosa gastronomía y recorrer sus encantadoras calles llenas de historia. Sin duda alguna, Bochalema posee un encanto especial que cautiva a quienes tienen la oportunidad de conocerlo.	\N	/static/municipalitie/BOCHALEMA/image.jpg	/static/municipalitie/BOCHALEMA/background.jpg
3	BUCARASICA	"El Pueblito Pesebre de Norte de Santander"	Bucarasica, joya del Norte de Santander, El territorio era habitado por indígenas búcaros. Fundado por Benjamín Torrado y Raimundo Peñaranda en 1860. es un municipio lleno de encanto y tradición. Sus hermosos paisajes montañosos, su rica historia y su cálida gente hacen de este lugar un destino imperdible para aquellos que buscan conocer lo mejor de la región. Descubre en este artículo todo lo que Bucarasica tiene para ofrecer.\n\nEl municipio está situado en una zona montañosa de los Andes Orientales, lo que le brinda un paisaje natural impresionante. Bucarasica se encuentra a una altitud promedio de 2.500 metros sobre el nivel del mar, lo que se traduce en un clima fresco y agradable durante la mayor parte del año. La temperatura media anual ronda los 18°C, aunque puede variar dependiendo de la altitud y la época del año	\N	/static/municipalitie/BUCARASICA/image.jpg	/static/municipalitie/BUCARASICA/background.jpg
4	CACOTA DE VELASCO	"La Tierra de los Tiestos"	El Bello Municipio de Cácota  fue fundada 26 de octubre de 1555 por Ortún Velasco de Velázquez y este 26 de octubre 2021 cumplio 466 años de historia\n\nesta vez les llevaré a conocer un gran y magnifico lugar, visitamos la Hermosa Laguna de Cácota y disfrutamos de gente maravillosa del Pueblo. \n\nCácota esta Localizada a 108 km y a aproximadamente 3 horas de Cúcuta;  con una temperatura media de 15 °C. Tiene un Clima: 16° C y Altitud: 2.400 metros sobre el nivel del mar.\n\nSu ubicación privilegiada, rodeada de hermosos paisajes naturales, lo convierte en un destino turístico ideal para aquellos amantes de la naturaleza y las aventuras al aire libre. Además, su patrimonio arquitectónico y cultural, representado en sus iglesias coloniales y festividades tradicionales, nos invitan a sumergirnos en su rica identidad cultural. Aunque es un municipio pequeño, su encanto y calidez humana no pasan desapercibidos.\n Tiene grandes historias, mitos y leyendas que son\n\nLA PROCESION DE LAS ANIMAS\nLa han visto en el pueblo, y la han esuchado rezar camino al cementerio, Llamada "Celestina" cuentan los pobladores que sus cantos y rezos son escalofriantes y que dan una vuelta completa al pueblo. Dicen que estas anuncian la despedida de algún habitante.\n\nLA MECHOSA\nSu sola vestimenta causa escalofrios, lleva un bastón muy largo en el que se apoya para caminar, dicen que asusta a quienes se atraviesan en su camino, y quienes han logrado verla se desmayan. Cuentan que han asustado a muchos pobladores del Municipio.\n\nEL COJITO DE LOS LEÑOS\nCuentan que muchos pobladores lo han visto, es un enano que vive en un viejo tronco, Dicen que le falta una pierna y que camina dando brincos, su barba es larga y es de pelo crespo, Este vive en los montes y ataca a quienes destruyen los arboles viejos y podridos. Se dice que mata a las personas haciendoles cosquillas\n	\N	/static/municipalitie/CACOTA DE VELASCO/image.jpg	/static/municipalitie/CACOTA DE VELASCO/background.jpg
5	CHINÁCOTA	"La Casita Bonita de Norte de Santander"	Chinácota es un municipio colombiano ubicado en el departamento de Norte de Santander. Su temperatura media es 22 grados Celsius, su altitud va desde los 600 a los 3200 m s. n. m. y su población es de 18.858 habitantes, de los cuales 12.131 residen en la cabecera municipal y 6725 residen en el área rural.\n\nDista 40 kilómetros de Cúcuta, capital del departamento, y 521 kilómetros de Bogotá, capital de Colombia. Es el municipio más turístico de Norte de Santander, lo cual es denominado La casita bonita de Norte de Santander. \n\ncon un gran valor histórico y cultural. Su arquitectura colonial, sus calles empedradas y su imponente iglesia son testimonio de su pasado y hacen que los visitantes se sumerjan en una experiencia única. Además, su gastronomía típica, sus festividades tradicionales y su cercanía a hermosos paisajes naturales lo convierten en un destino imperdible para aquellos que deseen conocer la riqueza cultural y natural de la región	\N	/static/municipalitie/CHINÁCOTA/image.jpg	/static/municipalitie/CHINÁCOTA/background.jpg
6	CHITAGÁ	"El Valle de los Arrayanes"	El gran pueblito mágico de Chitaga fue fundado el 12 de Diciembre de 1804, es conocido como "El Valle de los Arrayanes"\n\nEstá ubicado a aproximadamente 125 km de mi querida Cúcuta a dos o tres horas estimadas. Se caracteriza por ser una población tranquila y tradicional, logrando así que el visitante viaje al pasado y disfrute de las costumbres que ofrece este mágico lugar. Cuenta con un complejo lagunar, donde pueden encontrar LA LAGUNA EL SALADO, LA LAGUNA COMAGUETA Y LA LAGUNA EL TAMBOR refugio de turistas y amantes de los paisajes, están incrustados en el PÁRAMO del Almorzadero\n\nSus imponentes paisajes montañosos hasta su variada oferta cultural y gastronómica, Chitagá ofrece una experiencia única que cautiva a propios y extraños. Ya sea explorando sus senderos ecoturísticos, visitando sus iglesias coloniales o degustando platos típicos, cada rincón de este municipio nos invita a sumergirnos en su encanto y a disfrutar de momentos inolvidables.\n\nSeguimos recorriendo cada rincón de mi Querido Norte de Santander para mostrarles la belleza que nos tiene para ofrecer, los paisajes son inigualables solo te queda disfrutar.\n	\N	/static/municipalitie/CHITAGÁ/image.jpg	/static/municipalitie/CHITAGÁ/background.jpg
7	GRAMALOTE	“El Pueblo que Renacio de las Cenizas”	Gramalote Es conocido como "EL PUEBLO QUE RENACE" , Fundado dos veces, la primera vez el 27 de noviembre de 1857, y la segunda en 1883 por Gregorio Montes.\n\nLes cuento que esta vez estamos y visitamos uno de los Pueblos más Caracteristicos de Nuestro Norte de Santander, El Pueblo que Renace, lleno de resilencia y capacidad de volver entre las cenizas. EL hermoso Pueblo de Gramalote o Nuevo Gramalote\n\nUbicado a solo 47 Km de Cúcuta, que es aproximadamente 1 hora y 40 minutos,Su temperatura media es de 23 °C y su altura de 1040 msnm.\n\nEl 16 de abril de 2012 se sentaron las bases para el trabajo de la reconstruccion del nuevo gramalote y El 20 de diciembre de 2016 podria decir que se fundó y el Nuebo Gramalote.\n	\N	/static/municipalitie/GRAMALOTE/image.jpg	/static/municipalitie/GRAMALOTE/background.jpg
8	LABATECA	"El Pueblo de los Volcanes de Dios"	Fundado el 11 de Noviembre de 1630 época en que fue elegida en parroquia. y fue constituida como municipio en 1930 y la primera persona encargada en manejar sus destinos fue Manuel José de Mora\n\nToches, esta vez, me fui a conocer y a disfrutar uno de los tantos Pueblitos Mágicos que tiene Nuestro Departamento, me fui a Visitar Labateca, en Norte de Santander, un pueblito que me encanto, me emociono y me sorprendio muchisimo.\n\nLocalizada a tan solo tan solo 113 KM de la ciudad Cúcuta, labateca tiene una altura de 1566 MSNM y una temperatura de 18°C. Es reconocido en la región por su delicioso café, la ganadería, sus incomparables cascadas que son maravillas ecoturísticas.\n\nLa ruta para llegar a Labateca, Es un poco dura, hecha para los que les gusta la aventura y la carretera destapada, Pero vale muchisimo la pena, conocer su Parque Principal y tambien las maravillas que tiene este hermoso pueblito.\n	\N	/static/municipalitie/LABATECA/image.jpg	/static/municipalitie/LABATECA/background.jpg
9	LOURDES	“El Pueblito Más Lindo del Mundo”	Lourdes es un pueblito acogedor que está ubicado en el Corazón de las Montañas de Norte de Santander. SU Temperatura media de 19 °C, localizado a 8 km de la capital del departamento, fundado en 1905 y erigido municipio en 1925.\n\nSu economía se basa en la agricultura, principalmente en el café, cultivo que es conocido en la región por ser orgánico, suave y con un sabor muy especial.  Si decides visitar este lindo municipio, debes incluir en tu lista de cosas por hacer, tomar una buena taza de café al desayuno o en la media tarde. Al igual si quieres llevar algo realmente Lourdense a tus amigos, una bolsa de café o productos derivados de él pueden ser una gran opción. A continuación, te dejamos la información de todo lo que necesitas saber de este conservador y bonito pueblo en Norte de Santander Colombia.\n\nCon su rica historia y cultura, sus hermosos paisajes y su cálida hospitalidad, esta localidad nos invita a disfrutar de experiencias únicas. Desde sus iglesias coloniales hasta sus festividades tradicionales, Lourdes nos sumerge en una atmósfera llena de tradición y autenticidad. Además, sus atractivos naturales\n	\N	/static/municipalitie/LOURDES/image.jpg	/static/municipalitie/LOURDES/background.jpg
10	MUTISCUA	"La Capital Truchicola de Colombia”	El Municipio de Mutiscua  fue fundado el 25 de diciembre de 1841 Por Patricio Villamizar, Lo que hoy es mutiscua, era un territorio divido entre Pamplona y Silos.\n\nEl hermoso Municipio de Mutiscua Esta ubicada a aproximadamente 102 Km de Cúcuta y a unos 2600 MSNM, Tiene una temperatura promedio de 14 grados.\n\nEl camino hacia el hostal, es Maravilloso, por que te encuentras con paisajes inigualables, un clima espectacular, que te hará pensar lo maravilloso y diverso que es Nuestro Departamento.\n\nSu clima es frio, Pero un frio que amaña, que te deja disfrutar de las diferentes actividades, que se puede hacer, como senderismo por caminos reales, conocer todo el termianar pueden conocer la Hermosa Laguna Rabicha que queda aproximadamente 20 Minutos del hostal.\n	\N	/static/municipalitie/MUTISCUA/image.jpg	/static/municipalitie/MUTISCUA/background.jpg
11	PAMPLONA	“La Ciudad Neblina del Departamento”	Pamplona, es un frío y bonito municipio que queda en Norte de Santander, departamento de Colombia. Es conocida como la “Ciudad Estudiantil” debido a la presencia de la institución que lleva el mismo nombre, Universidad de Pamplona; que fue inaugurada en 1960.\n\nTambién es llamada como “Ciudad Mitrada”; la “Mitra” es la prenda con la que se cubre la cabeza personas con una larga trayectoria y jerarquía en la iglesia católica, como es el arzobispo u obispo; personas con roles muy importantes en la religión al igual que pamplona en los inicios del catolicismo en Norte de Santander, ya que fue primera diócesis católica en la región sur-occidente del Departamento.\n\nSu historia rica y sus encantadoras calles coloniales nos transportan a épocas pasadas, mientras que su gente hospitalaria y su ambiente tranquilo nos hacen sentir bienvenidos. Además de su patrimonio cultural, Pamplona también cuenta con hermosos paisajes naturales, que invitan a explorar y disfrutar de la belleza de la región. Sin duda, este municipio es un tesoro que merece ser descubierto y valorado por todos aquellos que buscan sumergirse en la historia, cultura y naturaleza del norte de Santander.\n	\N	/static/municipalitie/PAMPLONA/image.jpg	/static/municipalitie/PAMPLONA/background.jpg
12	SALAZAR DE LAS PALMAS	“La Cúna del Café del Departamento”	Salazar de las Palmas fue fundado el 04 de noviembre de 1853 por Alonso Esteban Rangel y era llamada Villa Nirva del Collado\n\nEsta vez nos fuimos a conocer y a disfrutar uno de los pueblitos Mágicos de Nuestro Norte de Santander, el Hermoso Pueblito de Salazar de Las Palmas.\n\nLocalizado a 56 km de San José de Cúcuta, presenta una temperatura de 24 °C. y Salazar tiene diferentes planes para hacer, bien sea simplemente un día de paseo, o todo un fin de semana\n\nSe dice que en Salazar de las Palmas se inició la industria cafetera de Colombia, siendo este el principal producto agrícola del municipio.\n\nSalazar de las Palmas tiene un encanto, adornada su hermoso parque principal con mas de 20 palmas, que lo hacen ver magico y hermoso, tienes que disrutar este pueblito magico que tiene nuestro Departamento\n\nCada vez que vayas a algun lugar mágico, pide permiso para entrar, ya que la naturaleza te escucha, ve con la menor vibra positiva y disfruta, admira y respeta lo que nos ofrece nuestro planeta\n\nSalazar de Las Palmas es un municipio que resalta en el contexto de los municipios del Norte de Santander por su riqueza cultural, histórica y natural. Su ubicación estratégica, sus tradiciones arraigadas y su gente acogedora hacen de este lugar un destino ideal para aquellos que buscan sumergirse en la belleza de los paisajes montañosos y descubrir la autenticidad de la región. Con su oferta turística diversa y sus atractivos como el Santuario de Nuestra Señora de Las Palmas y las festividades religiosas, Salazar de Las Palmas se ha convertido en un lugar de interés para visitantes nacionales e internacionales. Además, su gastronomía típica, con platos como la arepa de trigo y el famoso queso campesino, deleita los paladares más exigentes.\n	\N	/static/municipalitie/SALAZAR DE LAS PALMAS/image.jpg	/static/municipalitie/SALAZAR DE LAS PALMAS/background.jpg
13	SILOS	“El Pueblo Abuelo de Norte de Santander”\n	Con mas de 400 Años de Historia, Santo Domingo de Silos, es el Municipio Más Antiguo del Departamento, Fundado el 13 de julio de 1531 Es El único municipio fundado en Colombia por un alemán, Ambrosio Alfinger.\n\nLocalizado a 123 km de Cúcuta, con una temperatura media de 14 °C. y una altitud de 2845 m s. n. m.\n\nSe Caracteriza por salvaguardar su historia, costumbres y su cultura. El Municipio se caracteriza por la gran riqueza de patrimonio cultural intangible expresado en tradición oral, historia, danza, música, festividades y eventos\n\nsu patrimonio arquitectónico, representado por la iglesia de Santo Domingo de Silos, refleja la importancia religiosa y cultural del lugar. Asimismo, la calidez de su gente y la gastronomía típica hacen de este municipio un destino imperdible para aquellos que desean conocer y explorar el Norte de Santander. En definitiva, Santo Domingo de Silos es un tesoro oculto que merece ser descubierto y valorado por todos los amantes de la historia, la naturaleza y la cultura\n	\N	/static/municipalitie/SILOS/image.jpg	/static/municipalitie/SILOS/background.jpg
14	TOLEDO	"El Municipio Ganadero de Norte de Santander"	Toledo es un encantador municipio ubicado en el departamento de Norte de Santander, al norte de Colombia. Este hermoso lugar se encuentra rodeado de imponentes montañas y paisajes naturales que lo convierten en un destino ideal para los amantes del turismo rural.\n\nUno de los principales atractivos de Toledo es su riqueza natural. El municipio cuenta con una gran variedad de ecosistemas, como bosques, ríos y cascadas, que brindan un ambiente propicio para la práctica de actividades al aire libre, como senderismo, avistamiento de aves y paseos en bicicleta.\n\nLos conquistadores dominaron sin mayor resistencia a los primitivos indígenas, que huyendo, habían llegado a estos valles donde se conformaban con proveerse de los alimentos, que en esencia consistían el maíz, yuca, batata y varias frutas silvestres, cazaban venados y otros animales monteses cuya carne era muy apreciada.\n\nLa existencia y fundación de Labateca como encomienda se remonta hacia 1555 y 1560.\n\nToledo fue elevado a categoría de cabecera municipal en el año de 1886, pero su fundación data de 1795 cuando fue segregado como parroquia procedente de su vecino Labateca.\n\nSu ubicación estratégica en la región lo convierte en un destino perfecto para aquellos que deseen explorar la belleza natural de los Andes, mientras disfrutan de la hospitalidad y calidez de su gente. Además, su patrimonio arquitectónico y cultural brinda una experiencia enriquecedora para los amantes de la historia y la tradición. Sin duda, Toledo es un lugar que merece ser descubierto y valorado por todos aquellos que deseen adentrarse en la fascinante diversidad del Norte de Santander.	\N	/static/municipalitie/TOLEDO/image.jpg	/static/municipalitie/TOLEDO/background.jpg
\.


--
-- TOC entry 4815 (class 0 OID 16712)
-- Dependencies: 222
-- Data for Name: places; Type: TABLE DATA; Schema: public; Owner: cucutoche
--

COPY public.places (id, municipality_id, name, information, video, image, background) FROM stdin;
13	5	LAS NUBES GLAMPING	a tan solo cinco minutos del parque principal de chinacota\n\nVisitar las Nubes, es soñar, Es relajarse… Divertirse y pasarla increíble con las personas que aprecias…\n\nLAS NUBES COCINA BAR GLAMPING un lugar inolvidable en Chinácota.Ven y haz una pausa, degusta nuestras comidas y bebidas y descubre las maravillas que tenemos para ti. 	static/municipalitie/CHINÁCOTA/places/LAS NUBES GLAMPING/video.mp4	static/municipalitie/CHINÁCOTA/places/LAS NUBES GLAMPING/image.jpg	static/municipalitie/CHINÁCOTA/places/LAS NUBES GLAMPING/background.jpg
19	6	LAGUNA EL TAMBOR	La Laguna El Tambor se encuentra ubicada a 3825 MSNM, en la Vereda presidente a 30 minutos aproximadamente del Casco Urbano del Municipio de Chitagá Y para llegar a ella, es un verdadero reto y aventura,\n\nToches, esta vez nos fuimos a visitar una de las Joyas de La Corona de nuestro Departamento y el reto fisico más dificil que he enfrentado desde que estoy con el proyecto, Nos fuimos para el Pueblito Mágico de Chitagá a Visitar la HERMOSA LAGUNA EL TAMBOR\n\nSí quieres conocer y vivir esta aventura, deveras caminar por senderos y caminos empedrados y colchones de agua aproximadamente 03:00 Horas, pero vale muchísimo la pena, porque observaras paisajes increíbles que te llenan de alegría y felicidad, y a su vez te dejan anidado y con la boca abierta de tan maravillosos paisajes.\n\nEs importante cuando vayan a visitar estos lugares, realizarlo con guia, ya que son los que siempre están presentes en todo momento para ayudarte y cuidarte esta vez nos acompañó un guia \n	static/municipalitie/CHITAGÁ/places/LAGUNA EL TAMBOR/video.mp4	static/municipalitie/CHITAGÁ/places/LAGUNA EL TAMBOR/image.jpg	static/municipalitie/CHITAGÁ/places/LAGUNA EL TAMBOR/background.jpg
4	2	CASCADAS DE BOCHALEMA	En mi Viaje por Norte de Santander y más específicamente Bochalema, Les traigo las Cascadas que debes conocer en este hermoso pueblito mágico\n\nToches les cuento que en mi viaje por Bochalema, me fui a visitar las 3 hermosas cascadas que tiene el Municipio para conocer, y estas fueron:\n-Cascada El Edén\nEsta hermosa Cascada esta a pie de carretera, por la misma via a la cascada la peronia, esta sobre la ruta, solo se logra observar cuando cae demasiada agua\n\n-Cascada La Peronía\nEsta hermosa cascada queda ubicada a tan solo 25 minutos, por la via que va hacia el mirador, una cascada refrescante que da vida al pueblo\n\n-La Laja de la Llorona\nUna Increible Cascada de Bochalema, a aproximadamente 5 minutos del pueblo y de una caminata de 45 minutos por el Sendero Ecologico Agua Blanca\n\n\n	static/municipalitie/BOCHALEMA/places/CASCADAS DE BOCHALEMA/video.mp4	static/municipalitie/BOCHALEMA/places/CASCADAS DE BOCHALEMA/image.jpg	static/municipalitie/BOCHALEMA/places/CASCADAS DE BOCHALEMA/background.jpg
2	1	CASCADA CHICAGUA	La Cascada de Chicaguá está ubicada en la vereda del mismo nombre, y está a una hora del casco urbano del municipio de Arboledas. Y para llegar a ella Puedes ir en automóvil o moto hasta la escuelita Chicaguá que está a 20 min, para luego de allí caminar 45 minutos aproximadamente y encontraras una cascada imponente y mágica\n\nLa cascada tiene una altura aproximada de 60 metros, es realmente imponente por su altura, y el agua es demasiado fría pero relajante. Atrévete a visitarla. Vale la Pena\n	static/municipalitie/ARBOLEDAS/places/CASCADA CHICAGUA/video.mp4	static/municipalitie/ARBOLEDAS/places/CASCADA CHICAGUA/image.jpg	static/municipalitie/ARBOLEDAS/places/CASCADA CHICAGUA/background.jpg
1	1	CASCADA BARRIENTOS	La Cascada de Barrientos esta ubicada en el Corregimiento de Barrientos, entre Salazar y Arboledas, un magnífico paisaje y naturaleza de admirar.\n\nSe accede por un camino destapado que está ubicado a unos metros de la vía principal, son aproximadamente 30 minutos por el camino en moto, y luego unos 20 a 30 minutos caminando.\n\nSoy un amante de la naturaleza, de las Cascadas, de ver lo grande y majesutoso que es la naturaleza, cada vez que halla la oportunidad de conocer una nueva cascada, no la.pierdo por que son simplemente espectaculares.\n	static/municipalitie/ARBOLEDAS/places/CASCADA BARRIENTOS/video.mp4	static/municipalitie/ARBOLEDAS/places/CASCADA BARRIENTOS/image.jpg	static/municipalitie/ARBOLEDAS/places/CASCADA BARRIENTOS/background.jpg
3	1	MIRADOR LA LOMA	\n\nEl mirador de la loma de la cruz esta Ubicado en el Pueblito Mágico de Arboledas a tan solo 15 minutos del Parque Principal es un Lugar donde se puede apreciar las majestuosas montañas que adornan el bello municipio de Arboledas.\n	static/municipalitie/ARBOLEDAS/places/MIRADOR LA LOMA/video.mp4	static/municipalitie/ARBOLEDAS/places/MIRADOR LA LOMA/image.jpg	static/municipalitie/ARBOLEDAS/places/MIRADOR LA LOMA/background.jpg
5	2	HOTEL SAN JERONIMO	\nEs uno de los lugares turísticos que debes visitar en BOCHALEMA. \n\nRodeado de naturaleza, piscina, quebradas hacen de hotel campestre San Jerónimo sea el sitio ideal para disfrutar unas vacaciones en familia \n\nEl Hotel Campestre San Jerónimo, ubicado en el encantador municipio de Bochalema, Norte de Santander, es el destino ideal para quienes buscan una experiencia de descanso en plena naturaleza. Este acogedor hotel ofrece un ambiente familiar lleno de distracción, naturaleza y relajación.\n\nEntre sus principales servicios, el hotel cuenta con cabañas para parejas y familias, una refrescante piscina, una cascada natural y la oportunidad de interactuar con animales, brindando una experiencia única para grandes y chicos. Además, su restaurante ofrece deliciosas opciones gastronómicas para complementar su estadía.\n\nEl Hotel Campestre San Jerónimo es un lugar turístico que debes visitar en Bochalema. Rodeado de naturaleza, piscina y quebradas, hacen de este hotel campestre el sitio ideal para descansar y disfrutar de un ambiente natural.\n\nSi buscas un espacio de relax y ambiente natural, el Hotel San Jerónimo es tu mejor opción. Con cómodas habitaciones y un entorno tranquilo, es el lugar perfecto para desconectar y disfrutar de la serenidad que ofrece la naturaleza	static/municipalitie/BOCHALEMA/places/HOTEL SAN JERONIMO/video.mp4	static/municipalitie/BOCHALEMA/places/HOTEL SAN JERONIMO/image.jpg	static/municipalitie/BOCHALEMA/places/HOTEL SAN JERONIMO/background.jpg
6	2	STATUS COUNTRY	Status Country es un Restaurante Campestre, comida tipica e internacional, entre semana platos ejecutivos, vinos, licores y café. para pasar una tarde Romantica o en Familia, en un clima templado muy agradable.\n\nUbicado a 1 km antes de llegar a Bochalema o 800 metros después de la virgen, los esperamos con nuestra deliciosa comida y bellas instalaciones.Tenemos espacios naturales para que tus momentos o tus comidas sean de relax total.\n\nPuedes Vivir tus celebraciónes especiales en status country y serán inolvidables.	static/municipalitie/BOCHALEMA/places/STATUS COUNTRY/video.mp4	static/municipalitie/BOCHALEMA/places/STATUS COUNTRY/image.jpg	static/municipalitie/BOCHALEMA/places/STATUS COUNTRY/background.jpg
7	3	CASCADA LA CURVA	La Cascada la Curva, conocida tambien como la cascada La San Juana, es el lugar indicado y es un magnífico lugar para que lo visites con tus amistades.\n\nPara llegar se debe llegar al puente metalico a entrada es como nos gusta a nosotros es gratis El senderimos es de 30 a 45 minutos más o menos dependiendo de su ritmo de caminata Nuestro guia fue David, y no llevabamos ni 5 minutos y ya estabamos perdidos\n\nAhora si les digo toches la caminata, es bastante exigente asi que tienen que venirse preparados Tanto fisica como mentalmente, la recomendación  para el senderismo, es primero LLevar ropa comoda, botas para un mejor agarre, aguita para la hidratación y Bocadillo\n\nlo que le rescato a esta caminata es la vista tan impresionante y hermosa que nos regalaba Al terminar de subir la montaña, hay un descenso prolongado, tengan cuidado, y llegamos Hasta este pequeño rio, dode hay que mojarse, recomendación traer lazo para pasar Y al pasar seguimos rio arriba, que ya estaremos por llegar, les cuento que\n\ncon los que vayan, tienen que convertirse y ser una familia, ya que hay que ayudarse entre todos Vamos a llegar a este punto, a estas bonitas cascadas, pasamos por un lado con cuidado lo unico que queda es subir, por eso es importante es traer el lazo , subimos y bajamos con cuidado\n\n\n\n	static/municipalitie/BUCARASICA/places/CASCADA LA CURVA/video.mp4	static/municipalitie/BUCARASICA/places/CASCADA LA CURVA/image.jpg	static/municipalitie/BUCARASICA/places/CASCADA LA CURVA/background.jpg
8	3	CASCADAS LOS LAMENTOS	Un trío de cascadas escondidas dentro de las  montañas del municipio de Bucarasica. Ubicada a aproximadamente 2 horas del pueblo en un senderismo exigente, son una de las bellas y hermosas cascadas que adornan nuestro hermoso departamento\n\nPara llegar no es nada facil, pero eso es lo que hace increible este viaje, por que los caminos dificiles siempre nos llevan a lugares inigualables \n\n	static/municipalitie/BUCARASICA/places/CASCADAS LOS LAMENTOS/video.mp4	static/municipalitie/BUCARASICA/places/CASCADAS LOS LAMENTOS/image.jpg	static/municipalitie/BUCARASICA/places/CASCADAS LOS LAMENTOS/background.jpg
9	4	LAGUNA DE CÁCOTA	La laguna de Cácota o laguna el Cacique es un ecosistema acuático natural con un área aproximada de 1.5 hectáreas, situada a 2.900 m.s.n.m en la vereda Mata de Lata del municipio de Cácota, a cinco kilómetros del casco urbano.\n\nPara llegar a la Laguna de Cácota hay dos opciones, la primera es para lo más aventureros;  es a pie por el “Camino Real”, y puedes llegar a tardar entre una 1h u 1h 30 min  La segunda es en auto por una vía alternativa en buen estado que te permite estar allí en menos de 15 minutos. El valor del transporte en una camioneta puede costar $5.000 COP.\n\nPara terminar este gran hermoso viaje, faltaba una aventura más, Montar a Caballo, es mi primera vez que lo hacia, y me dio miedo al Principio, Bajando por el Camino Real, nos ofrecieron bajar en caballos y no lo dudamos. Es una experiencia Inolvidable\n\nes un destino que enamora con la majestuosidad de su paisaje, el contacto con la naturaleza y el encanto de sus historias \n	static/municipalitie/CACOTA DE VELASCO/places/LAGUNA DE CÁCOTA/video.mp4	static/municipalitie/CACOTA DE VELASCO/places/LAGUNA DE CÁCOTA/image.jpg	static/municipalitie/CACOTA DE VELASCO/places/LAGUNA DE CÁCOTA/background.jpg
31	9	Pozo La Pailona	El pozo la pailona es un pozo natural con las aguas más cristalinas de Norte de Santander, Se llega por la vía que de Sardinata conduce a Lourdes, aprox 30 minutos de carretera destapada hasta llegar al puente de la quebrada la Pailona, desde ahí subimos un sendero aprox. 5 minutos\n	static/municipalitie/LOURDES/places/Pozo La Pailona/video.mp4	static/municipalitie/LOURDES/places/Pozo La Pailona/image.jpg	static/municipalitie/LOURDES/places/Pozo La Pailona/background.jpg
10	4	LAGUNAS EL CORNAL	Las Lagunas El Cornal se encuentran ubicadas a Aproximadamente 3800 MSNM en un punto exacto y estratégico, ya que se encuentran entre la división de tres Municipios que son, Silos, Cacota de Velasco y Mutiscua.\n\nToches, esta vez, Estuvimos en uno de los lugares mas hermosos y fantasticos que he tenido la oportunidad de conocer, LAS HERMOSAS LAGUNAS, Una de las tantas lagunas que estan ubicadas en el MAJESTUOSO PÁRAMO DE SANTURBAN🍂\n\nPara acceder a ellas se debe caminar aproximadamente 01 hora y 20 minutos, y estan a 2 horas del parque principal de Mutiscua. En esta caminata, podras ver unos lugares magicos, lo imponente que es la madre tierra y lo vital que es cuidarla. Las lagunas las adornan con vegetación de Páramo.\n\nPara los amantes de la caminata, el senderismo , es un recorrido que deben realizar y visitar. Y poder experimentar lo que yo vivi rodeado de la naturaleza magica.\n\nEn ellas vemos vegetación de Páramo, todo bien adornado, con unos paisajes espectaculares que te dejarán sin aliento y con ganas de visisitar y disfrutar este grandioso lugar y tan hermoso Municipio.\n\nPara los amantes de la caminata, de la naturaleza y el senderismo es un recorrido que deben realizar, y experimentar lo que yo vivi rodeado de tan maravillosos paisajes y de lugares impresionantes.\n\nEstos dos grandiosos lugares, están en una ubicación geografica exacta , que limitan entre los Municipios de Cacota de Velasco, Silos y Mutiscua.\n	static/municipalitie/CACOTA DE VELASCO/places/LAGUNAS EL CORNAL/video.mp4	static/municipalitie/CACOTA DE VELASCO/places/LAGUNAS EL CORNAL/image.jpg	static/municipalitie/CACOTA DE VELASCO/places/LAGUNAS EL CORNAL/background.jpg
11	5	ALTO DEL MEJUE	Úbicado a Aproximadamente 1 hora del Casco Urbano del Municipio de Chinacota, el Alto o Páramo del Mejue, es uno de los lugares más espectaculares para visitar, conocer y recorrer por el Departamento de Norte de Santander. \n\nel alto del Mejue tiene la particularidad que da el fin de la Ruta de Chinacota y el Comienzo de la Ruta hacia el Municipio de Toledo, con una carretera, de camino destapado, increible.\n\nMientras vas subiendo y llegando al lugar, te abriga una neblina impresionante que te va acompañando por todo el recorrido, Donde te adentraras en una aventura increible, la mejor sensación para los viajeros, y más si la visitas en moto. \n\nAl llegar al Páramo, encontraras Una Tenda, donde podras toma un cafecito caliente, entrar y disfrutar de las maravillas del Lugar, tiene un bosque donde puedes caminar y ver lo increible que es la naturaleza.\n\nEn el recorrido, hay un mirador donde puedes observar todo el lugar, y es especial para tomarse unas fotos muy epicas y espectaculares, Me paso a mi que en todo momento queria tomarme fotos, ya que el lugar es especialmente mágico, te atrapa y no te quieres ir.\n\nEl  lugar es 100% recomendado, lo importante es que vayan a disfrfutar la ruta, el lugar, importante ir bien abrigado, ya que siempre hace mucho frio, se puede acceder en carro y en moto sin ningun problema. \n	static/municipalitie/CHINÁCOTA/places/ALTO DEL MEJUE/video.mp4	static/municipalitie/CHINÁCOTA/places/ALTO DEL MEJUE/image.jpg	static/municipalitie/CHINÁCOTA/places/ALTO DEL MEJUE/background.jpg
12	5	ENTRE FLORES	Situado cerca al paramo del Mejue, el Glamping Entre Flores ofrece todas las comodidades que necesitas para pasar una buena noche de descanso en zonas de montaña, con una hermosa vista y cielos estrellados.\n\nEl Glamping Entre Flores se encuentra ubicado en la vereda de Iscala Sur en el municipio de Chinacota, la zona más turística y conocida del departamento Norte de Santander.  Aproximadamente a 1 hora con 45 min de Cúcuta N.S.\n\nEl el Glamping Entre Flores podrás encontrar una variada carta de platillos y postres deliciosos durante el día y la noche, con espacios naturales y una entrada hermosa para tomarte las mejores selfies.\n\nUn ambiente familiar, espectacular para fines de semana buen ambiente, comida buen sabor, precios accesibles! Disfruta este espacio	static/municipalitie/CHINÁCOTA/places/ENTRE FLORES/video.mp4	static/municipalitie/CHINÁCOTA/places/ENTRE FLORES/image.jpg	static/municipalitie/CHINÁCOTA/places/ENTRE FLORES/background.jpg
14	5	MONTAÑA DE LA REFLEXIÓN	Esto se trata de un largo recorrido el cual nos permite conectarnos con la madre naturaleza, también nos ayuda a ver cuales son nuestras pasiones y nuestras virtudes para que al final del camino deshacernos de esas pasiones vanas y acoger más nuestras virtudes, el recorrido nos enseña que siempre va a estar el camino fácil para llegar a esas pasiones vanas y el camino difícil nos lleva a nuestras mayores virtudes para ser unas personas de bien.\n\nTambién encontramos un mirador de una mano gigante, donde se ve todo el pueblito chitarero. Una cruz, un corazón, un girasol, entre otras cosas bonitas.	static/municipalitie/CHINÁCOTA/places/MONTAÑA DE LA REFLEXIÓN/video.mp4	static/municipalitie/CHINÁCOTA/places/MONTAÑA DE LA REFLEXIÓN/image.jpg	static/municipalitie/CHINÁCOTA/places/MONTAÑA DE LA REFLEXIÓN/background.jpg
15	5	SSKY PARK	SSKY PARK es un parque de aventura extrema ubicado en chinacota, diseñado para que toda la familia se divierta.\n\npodrás vivir una experiencia increíble divertida y segura, se encuentran ubicados a tan solo 15 minutos del parque principal de chinacota por la vía que lleva al hotel Resort la montaña\n\n¡Allí encontraras todo un circuito de obstáculos algunos adaptados para niños y otros más aventureros para los grandes!	static/municipalitie/CHINÁCOTA/places/SSKY PARK/video.mp4	static/municipalitie/CHINÁCOTA/places/SSKY PARK/image.jpg	static/municipalitie/CHINÁCOTA/places/SSKY PARK/background.jpg
16	6	COMPLEJO DE LAGUNAS BURGUA	El COMPLEJO BURGUA, ESTA Ubicado a Chitagá a aproximadamente 1 hora en moto, y 2 horas caminando, Se encuentra este complejo LAGUNAR, a casi 4000 MSNM, La caminata es extrema, dura, dificil, pero los resultados valen la pena, el paisaje es maravilloso e increíble.\n\nAparte de las lagunas mencionadas, en la caminata verás tres lagunas más que son increíbles y maravillosas y les dejare el contaco del guia, para que puedan visitar este hermoso lugar.\n\nEstas son las Hermosas Lagunas que puedes encontrar en El complejo Lagunar Burgua del Páramo del Almorzadero en Chitagá\n- Laguna El Alto de las Cruces\n- Laguna de Arco\n- Laguna Negra\n- Laguna La Barrosa\n- Laguna de Ojos\n\nPara mi Este es el LUGAR MÁS IMPRESIONANTE de Norte de Santander\n	static/municipalitie/CHITAGÁ/places/COMPLEJO DE LAGUNAS BURGUA/video.mp4	static/municipalitie/CHITAGÁ/places/COMPLEJO DE LAGUNAS BURGUA/image.jpg	static/municipalitie/CHITAGÁ/places/COMPLEJO DE LAGUNAS BURGUA/background.jpg
32	9	Santuario de Lourdes	EL Santuario Nuestra Señora de Lourdes, Fundado en el año 2009, ubicado en la Vereda Volcanes lugar donde se apareció la imagen de La virgen en una tabla.\n	static/municipalitie/LOURDES/places/Santuario de Lourdes/video.mp4	static/municipalitie/LOURDES/places/Santuario de Lourdes/image.jpg	static/municipalitie/LOURDES/places/Santuario de Lourdes/background.jpg
17	6	LAGUNA COMAGUETA	Ubicada en la vereda de presidente en el municipio de Chitaga, A una distancia de aprox de 145 kms desde la ciudad de Cúcuta, en un recorrido de aprox 4 horas en vehículo🏍️🚗\n\nToches, en mi viaje visitando Chitagá, Me fui a conocer una de Las fantasticas lagunas que tiene este pueblito, me fui a conocer el Rincon de la Comagueta, donde admire la hermosa Laguna Comagueta, que les cuento que quede encantado con el paisaje, la paz y la tranquilidad que se siente en el lugar.\n\nLa Laguna Comagüeta es de origen glacial y es un refugio para los turistas amantes de los paisajes de alta montaña, Podrás disfrutar de cabañas y una excelente gastronomía\n\nLo bonito de esta Laguna, es que pueden ver Cisnes, que lo dejan a uno maravillado, y con ganas de quedarse mucho más. La verdad fué una maravilla de lugar\n	static/municipalitie/CHITAGÁ/places/LAGUNA COMAGUETA/video.mp4	static/municipalitie/CHITAGÁ/places/LAGUNA COMAGUETA/image.jpg	static/municipalitie/CHITAGÁ/places/LAGUNA COMAGUETA/background.jpg
18	6	LAGUNA EL SALADO	La Laguna El Salado Esta ubicada en el Corregimiento de Presidente a tan solo 3.476 MSN, es uno de los principales atractivos turísticos de Chitagá en nuestro hermoso Páramo del Almorzadero.\n\nToches, les comento que me fui a Visitar la Joya de la Corona del Chitagá, Nos fuimos a Recorrer la Hermosa y única Laguna El Salado Que me dejo impresionado, de su tal magnitud y de lo hermosa que es la Laguna.\n\nEl agua de esta laguna es transparente con problemas de oxigenación, por la abundancia de algas. La temperatura media superficial es de 12 grados centígrados. Sus riveras son pantanosas en el sector sur, mientras que, en el resto del entorno, se presentan firmes.\n	static/municipalitie/CHITAGÁ/places/LAGUNA EL SALADO/video.mp4	static/municipalitie/CHITAGÁ/places/LAGUNA EL SALADO/image.jpg	static/municipalitie/CHITAGÁ/places/LAGUNA EL SALADO/background.jpg
20	7	CASCADA ARCOIRIS	Ubicada el Municipio de Gramalote a Excasos 20 minutos del Casco Urbano, en el complejo de Cascadas, esta esta hermosura, LA CASCADA ARCOIRIS y deberas CAMINAR aproximadamente 15minutos, por un sendero bien señalizado, hasta la Cascada, podras observar naturaleza en todo su esplendor y disfrutar de un senderismo ecológico\n\nUna de las Maraviilas de Nuestro Departamento y la Joya de la corona del Pueblito Mágico de Gramalote, Es la Hermosa Cascada Arcoiris, que realmente son hermosas y valen la pena visitar.\n\nPara Ingresar y conocer esta hermosa cascadas  Se debera cancelar un valor de $5.000 por persona, y podras disfrutar de todo el complejo, Les recomiendo muchisimo que visiten esta hermosa cascada.\n\nEn cada Rinconcito de Norte de Santander, puedes enconrtar lugares increibles y mágicos, solo te toca a ti, atreverte a buscarlos y darte la satisfacción de ser uno con la Madre tierra, y compartir grandes aventuras. Arma tu parche con tu familia y amigos, conoce, diviertete\n	static/municipalitie/GRAMALOTE/places/CASCADA ARCOIRIS/video.mp4	static/municipalitie/GRAMALOTE/places/CASCADA ARCOIRIS/image.jpg	static/municipalitie/GRAMALOTE/places/CASCADA ARCOIRIS/background.jpg
21	7	LAGUNA POZO LARGO	Ubicado en el Nuevo Gramalote, a tan solo 10 Minutos del Pueblo, debes buscar la Planta de Tratamiento de Agua, para ahi comenzar el Senderismo que te llevara a Pozo Largo\n\nDespues de Llegar a La planta de Tratamiento de agua, deberas seguir un sendero de Aproximadamente 20 minutos montaña arriba, que es un poco dificil, pero te dara una vistas impresionantes y la recomepensa es maravillosa.\n	static/municipalitie/GRAMALOTE/places/LAGUNA POZO LARGO/video.mp4	static/municipalitie/GRAMALOTE/places/LAGUNA POZO LARGO/image.jpg	static/municipalitie/GRAMALOTE/places/LAGUNA POZO LARGO/background.jpg
22	7	POZO EL MOLINO	POZO "EL MOLINO" Ubicado en el municipio de Gramalote en NortedeSantander Como llegar De Cúcuta dista aproximadamente 2 horas se hace desvío por la vía gramalote viejo se llega al matadero municipal luego pasando el antiguo estadio del municipio a mano derecha esta la entrada; se camina aproximadamente 15 minutos para llegar. \n \nTe presentamos el pozo del molino un lugar turístico por tradición, un pozo lleno de historias de amor, con sus aguas coloradas de rojo y sus piedras imponentes sobre el rio.\n	static/municipalitie/GRAMALOTE/places/POZO EL MOLINO/video.mp4	static/municipalitie/GRAMALOTE/places/POZO EL MOLINO/image.jpg	static/municipalitie/GRAMALOTE/places/POZO EL MOLINO/background.jpg
30	9	Cascada Guaimaral	La CASCADA GUIAMARAL Ubicada a tan Solo media hora del Pueblo, con la ruta que comunica hacia Sardinata, Esta esta Hermosa Cascada, que podras disfrutar en familia y amigos.. Para Ingresar a la Cascada, Deberas cancelar $5.000 COP, y podras disfrutar de unas de las maravillas de mi Norte de Santander. \n\nTambien, puedes encontrar, Restaurante para que armen su plan completo del día toches en el Pueblito Más Lindo del Mundo. Quede encantado y maravillado te tan hermoso lugar y se los recomiendo muchisimo, Un lugar más de mi Norte.\n	static/municipalitie/LOURDES/places/Cascada Guaimaral/video.mp4	static/municipalitie/LOURDES/places/Cascada Guaimaral/image.jpg	static/municipalitie/LOURDES/places/Cascada Guaimaral/background.jpg
33	10	CABAÑA EL PINO	La cabaña el pino restaurante es una granja integral, un modelo de agricultura sostenible que es muy visitado por estudiantes que Agronomía y carreras a fines para conocer su funcionamiento\n\nEn el lugar se conjuga la protección de la naturaleza con la producción limpia, un proyecto de vida donde la señora Eliza entre truchas, conejos, gallinas, patos, vacas aromáticas, aves y muchas hortalizas nos muestra como llegan los alimentos del campo a la mesa y nos enseña el valor del trabajo del campo y sus sacrificios para poder producir alimentos de calidad. \n\nLa cabaña el pino brinda una experiencia agroturistica donde podrás probar a que sabe Mutiscua y sus diferentes productos, en especial la trucha que podrás pescar en el lugar. \n\nEsta ubicado en la vereda el Aventino de Mutiscua, por la entrada de las pagas en el km 93 de la vía\n	static/municipalitie/MUTISCUA/places/CABAÑA EL PINO/video.mp4	static/municipalitie/MUTISCUA/places/CABAÑA EL PINO/image.jpg	static/municipalitie/MUTISCUA/places/CABAÑA EL PINO/background.jpg
34	10	CASA CAMILO DAZA	La hacienda la caldera fue el lugar donde nació el héroe de la aviación colombiana Camilo daza Álvarez pionero de la aviación  colombiana y quien de niño se lanzó de uno de sus balcones tratando de volar\n\nLa hacienda fue habitada más adelante por un exiliado  alemán la segunda guerra mundial  de nombre Adolfo según relata... Ronaldo Ortiz Latorre columnista de vanguardia liberal \n\nPor su cabecera cruza el antiguo camino real que se ensancha cual autopista y por donde se movía el comercio en los siglos xvll y xvlll\n\nHoy día pertenece al iser Instituto de educación rural de pamplona quienes proyectan un centro de investigación de páramos y una casa museo donde se rinda tributo a este héroe nortesantandereano que tan el alto dejo el nombre del departamento\n	static/municipalitie/MUTISCUA/places/CASA CAMILO DAZA/video.mp4	static/municipalitie/MUTISCUA/places/CASA CAMILO DAZA/image.jpg	static/municipalitie/MUTISCUA/places/CASA CAMILO DAZA/background.jpg
23	7	RUINAS DE GRAMALOTE	El Antiguo Gramalote fué Fundado dos veces, la primera vez el 27 de noviembre de 1857, y la segunda en 1883 por Gregorio Montes.\n\nEsta vez los llevare a conocer y retrocederemos en el tiempo de lo que algun día fue EL MUNICIPIO DE GRAMALOTE y lo que hoy quedan las Ruinas del Antiguo Gramalote\n\nEl 17 de diciembre de 2010, el antiguo casco urbano del municipio de Gramalote, en Norte de Santander, se vino abajo debido a una falla geológica que destruyó por completo las viviendas de 3.500 habitantes.  Afortunadamente, Ninguno de los 6.000 habitantes de Gramalote murió en la tragedia, pero el pueblo quedó destruido.\n\nLo unico que se conserva del antiguo es una cúpula de lo que fue la hermosa iglesia San Rafael Arcángel y parte de lo que era el parque principal del municipio.\n\nUbicado a solo 47 Km de Cúcuta, que es aproximadamente 1 hora y 40 minutos,Su temperatura media es de 23 °C y su altura de 1040 msnm, y para llegar a las ruinas, se debe acceder por un camino destapado, solo 10 minutos y las encontraras y disfrutaras de lo que es historia pura del Departamento.\n\nSeguimos recorriendo cada rincón de mi Querido Norte de Santander, para mostrarles la belleza que nos tiene para ofrecer, los paisajes son inigualables solo te queda disfrutar y admirar.\n	static/municipalitie/GRAMALOTE/places/RUINAS DE GRAMALOTE/video.mp4	static/municipalitie/GRAMALOTE/places/RUINAS DE GRAMALOTE/image.jpg	static/municipalitie/GRAMALOTE/places/RUINAS DE GRAMALOTE/background.jpg
24	8	CASCADA ANGELINA	Cascada de la vereda de ANGELINA municipio de labateca norte santander los lugares que nuestra madre tierra nos ofrece orgullo de nuestro municipio\n\nse llega a la Vereda (Paradero) la Unión y se gira a mano derecha por la vía que conduce a la vereda Santa María, para posteriormente buscar la Vereda Balsa y luego la Vereda Angelina. La vía es totalmente destapada (Auto alto o moto), desde el desvío de la vía principal es un trayecto aproximado de una hora y media en vehículo y caminata de 15 minutos. Es supremamente importante que busques un guía ya que el terreno es difícil y puedes perderte. \n\nrecomienda viajar en tiempo seco ya que la quebrada puede llegar a ser muy abundante por las lluvias.\n	static/municipalitie/LABATECA/places/CASCADA ANGELINA/video.mp4	static/municipalitie/LABATECA/places/CASCADA ANGELINA/image.jpg	static/municipalitie/LABATECA/places/CASCADA ANGELINA/background.jpg
25	8	CASCADA DOS BRZOS	La Cascada Dos Brazos, Es una de las Maravillas Turisticas de Labateca y está ubicada a tan solo 15 minutos de la Cascada Lirgua, son dos caídas de agua, cada una con una altura aproximada de 20 Metros\n\nTOCHES, Les cuento, por eso les comenté en el Post Anterior que Labateca, era un Pueblito lleno de Increibles Cascadas, y Vean esta Hermosura que fui a conocer LA HERMOSA CASCADA DOS BRAZOS\n\nLa caminata para llegar a la Cascada es Corta pero exigente, pero al llegar encontraras una de las Cascadas más fascinantes de Nuestro Departamento ,toches Atrévanse a visitar esta hermosa cascada y cada vez más descubre lo maravilloso y increíble que es Norte de Santander\n	static/municipalitie/LABATECA/places/CASCADA DOS BRZOS/video.mp4	static/municipalitie/LABATECA/places/CASCADA DOS BRZOS/image.jpg	static/municipalitie/LABATECA/places/CASCADA DOS BRZOS/background.jpg
26	8	CASCADA EL CHORRERÓN	EL PARAÍSO OCULTO DE NORTE DE SANTANDER, EL CHORRERON \n\nLlegar al lugar es comprobar lo imponente que es esta hermosa cascada y observar que no son dos caídas de agua sino tres en donde ésta es la última y tiene más de los 70 metros de altura.Tomar fotos aquí no fue nada fácil ya que la brisa que corre es bastante fuerte.\n\nUna de las cascada más bonitas de Norte de Santander y se encuentra en el municipio de Labateca, exactamente en la vereda La Vegauna ruta de aprox 1hora y media donde te deja atrapar por la belleza de sus imponentes montañas y fascinantes paisajes  para poder llegar a este maravilloso lugar fuimos acompañados por una familia que viven en una vereda cercana, pero OJO, ellos no son guías, sin embargo si desean en algún momento conocer este lugar.\n	static/municipalitie/LABATECA/places/CASCADA EL CHORRERÓN/video.mp4	static/municipalitie/LABATECA/places/CASCADA EL CHORRERÓN/image.jpg	static/municipalitie/LABATECA/places/CASCADA EL CHORRERÓN/background.jpg
27	8	CASCADA LIRGUA	La Cascada Lirgua esta ubicada en la via Pamplona - Saravena a 30 minutos del Parque Princiapal de Labateca, tiene una altura de 60 mts aproximadamente,  La cascada se puede obserar desde su entrada \n\nToches, en el Viaje por LABATECA, me fui a conocer una de las joyas de la corona del Pueblo, que es la Hermosa Cascada LIRGUA, Les cuento que la pase increible, disfrute muchisimo, y los invito a vivir esta aventura.\n \nPara ingresar deberas cancelar $3.000 pesos, y observaras una de las Cascadas más hermosa de Nuestro Departamento y una de las Joyas de la corona de la Labateca. Toches deben venir a visitarla, disfrutar lo fria que es su agua, vale muchisimo la pena.\n\nLa caminata a la Cascada es de aproximadamente 5 minutos, donde el sendero esta muy bien demarcado, y observaras una de las cascadas mas hermosas de mi Departamento\n	static/municipalitie/LABATECA/places/CASCADA LIRGUA/video.mp4	static/municipalitie/LABATECA/places/CASCADA LIRGUA/image.jpg	static/municipalitie/LABATECA/places/CASCADA LIRGUA/background.jpg
28	8	CASCADA SISCATA	Es una cascada de 80 metros de altura ubicada en el noroccidente del municipio de Labateca, más específicamente en la Vereda La Laguna.\n\nPara llegar allí es necesario caminar una hora y media desde el casco urbano. Cerca al salto de Siscatá también es posible conocer la cueva del Cojito y pozos que antiguamente eran usados por indígenas para ritos y ceremonias.\n\nAlrededor de esta giran historias y leyendas de las cuales existe un respeto por parte de los propios y visitantes, gracias a que en la zona vivieron los indios Batecaque realizaban rituales de adoración al sol invocaban espíritus y demás practicas esotéricas.\n\nEs increíble ver tantos paisajes Espectaculares en lugares Tan remotos,  tras casi 2 horas de senderismo podría decir casi que extremo!  Nos topábamos con lugares donde podrían salir fotos increíbles, en las cuales quedarían plasmados hermosos recuerdos, el cansancio, sudor y el dolor de la caminata como la satisfacción de llegar a la meta y conocer tan hermosos lugares! \n	static/municipalitie/LABATECA/places/CASCADA SISCATA/video.mp4	static/municipalitie/LABATECA/places/CASCADA SISCATA/image.jpg	static/municipalitie/LABATECA/places/CASCADA SISCATA/background.jpg
29	9	Cascada Elefante	LA CASCADA ELEFANTE Es El Nuevo Atractivo Turístico en El Pueblito Más Lindo del Mundo, esta vez me vine a visitar y recorrer un pueblito mágico más, AL PUEBLITO MÁS LINDO DEL MUNDO , y también me vine a conocer EL NUEVO ATRACTIVO TURISTICO, la hermosa CASCADA ELEFANTE\n\nUbicada a tan solo 15 minutos, del Pueblo, La Cascada es uno de los Atractivos del Pueblo, La entrada tiene un valor de $5.000 Y se camina solo 10 minutos por un sendero bien señalizado. Se los recomiendo vale muchísimo la pena\n	static/municipalitie/LOURDES/places/Cascada Elefante/video.mp4	static/municipalitie/LOURDES/places/Cascada Elefante/image.jpg	static/municipalitie/LOURDES/places/Cascada Elefante/background.jpg
35	10	CASCADA EL CHORRERÓN	Comenzamos la caminata por el Sendero el Chorrerón, que dura aproximadamente 20 minutos y que nos llevara a la Cascada, un sendero muy bonito, muy verde, muy bien cuidado por los habitantes de Mutiscua,  la Cascada El Chorrerón, una maravilla de la naturaleza, de aproximadamente 50 metros de Altura, donde podrás darte un baño refrescante. \n\nDespués emprendimos caminata hacia Segunda Caída de la Cascada El Chorrerón. Muy bonita, aunque no es tan espectacular como la primera, pero vale la pena conocerla, y el agua es demasiado fría,\n\nNo se pierdan la oportunidad de conocer los hermosos y mágicos rincones que tiene nuestro hermoso departamento. Es importante no arrojar basuras en éstos lugares, realizar senderismo con responsabilidad es tarea de todos.\n	static/municipalitie/MUTISCUA/places/CASCADA EL CHORRERÓN/video.mp4	static/municipalitie/MUTISCUA/places/CASCADA EL CHORRERÓN/image.jpg	static/municipalitie/MUTISCUA/places/CASCADA EL CHORRERÓN/background.jpg
36	10	HOSTAL SHAMBALA	Úbicado en la Vereda la Aradita a aproximadamente 20 minutos del Casco Urbano de Mutiscua, Podran encontrar un lugar escondido en el Departamento el mágico y majestuoso Hostal Shambala. Alojamientos Rurales Shamba-La\n\nToches, esta vez les traigo una super recomedación, un lugar espectacular donde puedes pasar un fin de semana increible con tus familias y amigos a pocos minutos del Pueblito mágico de Mutiscua, el Hermoso y Acogedor Hostal Shambala\n\nEl camino hacia el hostal, es Maravilloso, por que te encuentras con paisajes inigualables, un clima espectacular, que te hará pensar lo maravilloso y diverso que es Nuestro Departamento. Su clima es frio, Pero un frio que amaña, que te deja disfrutar de las diferentes actividades, que se puede hacer, como senderismo por caminos reales, conocer todo el termianar pueden conocer la Hermosa Laguna Rabicha que queda aproximadamente 20 Minutos del hostal.\n\nEn el hostal, puedes encontrar el Glamping a diferentes precios, pero generalmente tiene un valor de $50.000 $ por pesona incluido el desayuno + servicio de guianza para senderismo por caminos reales y por pareja 150.000 en la cabaña.\n	static/municipalitie/MUTISCUA/places/HOSTAL SHAMBALA/video.mp4	static/municipalitie/MUTISCUA/places/HOSTAL SHAMBALA/image.jpg	static/municipalitie/MUTISCUA/places/HOSTAL SHAMBALA/background.jpg
37	10	LAGUNA RABICHA	Conocimos el Espejo Natural del Departamento La laguna Rabicha esta ubicada en la vereda la aradita municipio de Mutiscua aes un ecosistema de aves migratorias y esta ubicada en la Vereda Aradita en Mutisca Norte de Santander, es una pequeña laguna que pertenece al Majestuoso Páramo de Santurbán\n\nComenzaras una Caminata de unos 20 minutos aproximadamente, por senderos espectaculares bien demarcados, que en todo momento te daran ganas de tomarse fotos epicas para recordar los paisajes tan hermosos que vas encontrando por el camino,\n\nEl clima por lo general es frio, nublado y si tienen mucha suerte, podran contemplar toda la laguna en todo su esplendor.\n	static/municipalitie/MUTISCUA/places/LAGUNA RABICHA/video.mp4	static/municipalitie/MUTISCUA/places/LAGUNA RABICHA/image.jpg	static/municipalitie/MUTISCUA/places/LAGUNA RABICHA/background.jpg
38	11	DONDE DON SAMUEL	Donde Don Samuel es un increíble mirador donde su atractivo es la Mano de Gigante en Norte de Santander a solo 10 minutos de Pamplona.\n\nUn buen lugar para conocer en Pamplona Norte de Santander, La mano gigante. Finca donde Don Samuel, queda 5 km mas arriba de Pamplona, en la vía que va hacia Bucaramanga, hay cabañas, pool, tejo, bolos, espacio para acampar y un paisaje espectacular. Super recomendado.}\n	static/municipalitie/PAMPLONA/places/DONDE DON SAMUEL/video.mp4	static/municipalitie/PAMPLONA/places/DONDE DON SAMUEL/image.jpg	static/municipalitie/PAMPLONA/places/DONDE DON SAMUEL/background.jpg
39	11	MIRADOR EL RODEO	El “Sendero Ecológico El Rodeo”, ubicado a solo 7 km del Parque Principal, es el lugar perfecto para disfrutar de la naturaleza, recorrer senderos ecológicos, admirar panorámicas impresionantes de Pamplona y saborear la gastronomía tradicional.\n\nsendero ecologico a vivir una experiencia  diferente que no te puedes perder en pamplona disfrutando de un día campestre  con la mejor atención, ven a degustar nuestras deliciosas parrilladas, picadas  y hoy nuestro delicioso sancocho de gallina criolla criadas aqui, los esperamos para compartir en familia haciendo senderismo y disfrutando de la mejor panorámica de Pamplona desde nuestros miradores,  seras  otro mas de los cientos de clientes que se han ido felices con nuestra atencion domingos y festivo\n	static/municipalitie/PAMPLONA/places/MIRADOR EL RODEO/video.mp4	static/municipalitie/PAMPLONA/places/MIRADOR EL RODEO/image.jpg	static/municipalitie/PAMPLONA/places/MIRADOR EL RODEO/background.jpg
40	11	RANCHO LA FLORIDA	Restaurante Rancho La Florida los invita a disfrutar de la deliciosa picada 7 carnes, estamos ubicados frente al parque recreacional los tanques, los atendemos los diás sábados, domingos y festivos de 9 de la mañana a 3 de la tarde.\n\nA sólo una hora de Cúcuta, en la hermosa Pamplona, una pareja de cucuteños, Lauren Durán y Davied Rodriguez decidieron crear su emprendimiento Hace un año nació Rancho LaFlorida Restaurante Bar,  el cual además de ofrecer una deliciosa comida, donde las especialidad son las picadas mixtas, también se puede compartir en familia y gozar del delicioso clima de la ciudad mitrada del departamento.\n\nRestaurante, áreas naturales y de descanso hacen parte de este mágico lugar. Anímese mañana lunes festivo, cambie de clima y disfrute de un delicioso almuerzo.  El sazón de estos cucuteños y el frío envidiable de Pamplona los esperan.\n\nPicada 7 carnes: Carne de res, bondiola de Cerdo, Chicharrón, pechuga, morcilla, costillas de cerdo en canela, chorizo caramelizado, papá, yuca y Maduro acompañado de una deliciosa salsa Tártara y un pico'egallo Delicioso mute santandereano. \n	static/municipalitie/PAMPLONA/places/RANCHO LA FLORIDA/video.mp4	static/municipalitie/PAMPLONA/places/RANCHO LA FLORIDA/image.jpg	static/municipalitie/PAMPLONA/places/RANCHO LA FLORIDA/background.jpg
41	11	RESTAURANTE EL NORTEÑO	Con mas de 40 años de tradición el Restaurante El Norteños Puedes disfrutar de un ambiente Al aire libre y un dia diferente en compañía de sus amigos, de su parche de motos y su familia Descubriendo el placer de la buena comida., con su especialidad que es  la carne al barril  y unas picadas a la parrilla\n\nEl Restaurante el Norteño, es el lugar indicado y preferido por los pamploneses, para parchar y disfrutar una rica tarde diferente acompañando de su familia, de pareja y de su parche de viajes, deben venir la razon del por que volvimos al Norteño es para probar su nuevo producto, el famoso sancochito de gallina\n	static/municipalitie/PAMPLONA/places/RESTAURANTE EL NORTEÑO/video.mp4	static/municipalitie/PAMPLONA/places/RESTAURANTE EL NORTEÑO/image.jpg	static/municipalitie/PAMPLONA/places/RESTAURANTE EL NORTEÑO/background.jpg
42	12	CASCADA EL EJIDO	En Salazar de las palmas, puedes escaparte de la rutina. A 10 minutos de la vía principal, se encuentra la cascada el Ejido\n\nLlega a la virgen, avanza 5 minutos buscando el brazo del río a mano izquierda. Sube 15 minutos rio arriba y listo.\n\nEstas maravillas naturales son ideales para disfrutar de paisajes exuberantes, aguas cristalinas y aventuras ecoturísticas en medio de la naturaleza del Norte de Santander\n	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA EL EJIDO/video.mp4	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA EL EJIDO/image.jpg	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA EL EJIDO/background.jpg
43	12	CASCADA EL OSO Y MANDINGAS	CASADAEL MANDINGAS\nEsta aproximadamente a una hora y media del casco urbano de Salazar de las Palmas. Para llegar allí, se debe buscar el sendero Tesorito o el camino la Vereda Campo Nuevo. Se cree que esta hermosa cascada de Salazar de las Palmas tiene al menos 30 metros de altura. Si cuentas con suerte, es probable puedas ver fauna y flora que son características propias de la espeleología deportiva\n\nEsta fabulosa cascada además de ser muy hermosa, también es importante para los habitantes del pueblo de Salazar de las Palmas. ¿Por qué? De allí se obtiene el agua para el acueducto del casco urbano, por lo que para visitar esta maravilla natural con fines académicos se debe contar con AUTORIZACIÓN y ACOMPAÑAMIENTO de la Alcaldía Municipal.\n\nCASCADA EL OSO\nLa Increible, magica y Espectacular CASCADA eL OSO, Un paraiso escondido en las Montañas de Salazar de las Palmas a tan solo 15 minutico rio arriba, desde la cascada el mandingas \n	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA EL OSO Y MANDINGAS/video.mp4	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA EL OSO Y MANDINGAS/image.jpg	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA EL OSO Y MANDINGAS/background.jpg
44	12	CASCADA ERMITAÑO	La cascada ermitaño, esta ubicada en el pueblito magico de salazar en las palmas, A 2 horas del casco urbano, en la vereda la copa, con vía arboledas.\n\nUna de las Maraviilas de Nuestro Departamento y una de las CASCADAS menos conocida del Hermoso Pueblito de Salazar de las Palmas, Es la Hermosa Cascada ERMITAÑO, que realmente son hermosas y valen la pena visitar.\n\nPara llegar a ella deberas caminar 1 hora, donde estaras rodeado de naturaleza y paisajes increibles, Toches deben venir y visitar estas maravillas de la naturaleza de Norte de Santander.\n\nLuego de Visitar Salazar nos Fuimos a conocer una delas Cascadas Más Hermosas del Departamento, Nos fuimos a la CASCADA ERMITAÑO, Donde disfrutamos de una ruta increible, llena de adrenalina.\n\nLa cascada ermitaño, esta ubicada en el pueblito magico de salazar en las palmas, 2 horas del casco urbano, en la vereda la copa, con vía arboledas, a  la cascada tiene una altura de e 40 metros aproximadament , para llegar a ella deberas caminar 1 hora, donde estaras rodeado de naturaleza y paisajes increibles	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA ERMITAÑO/video.mp4	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA ERMITAÑO/image.jpg	static/municipalitie/SALAZAR DE LAS PALMAS/places/CASCADA ERMITAÑO/background.jpg
45	13	LAGUNA DE ANTALA	La Laguna de Antala Una importante reserva hidrica del Gran Santander, con más de 60 espejos de agua, hacen de este lugar, uno más de los encantos de Nuestro querido Silos, ubicada en la vereda del mismo nombre, a 3600 m sobre el nivel del mar y 3 horas de recorrido partiendo del casco urbano.\n\nLos paisajes del Sistema Lagunar Antala son realmente hermosos, con espejos de agua cristalina rodeados de afloramientos rocosos y áreas despejadas, lo que lo convierte en un destino ideal para el turismo contemplativo y de naturaleza. Sin embargo, es importante mencionar que el área requiere de un manejo adecuado de los visitantes para preservar su belleza y biodiversidad, ya que se han observado problemas con el manejo de desechos sólidos cerca al complejo.\n\nEs un lugar que invita a la reflexión sobre la importancia de cuidar nuestros recursos naturales y disfrutar de la tranquilidad que ofrecen estos paisajes únicos de Colombia.\n	static/municipalitie/SILOS/places/LAGUNA DE ANTALA/video.mp4	static/municipalitie/SILOS/places/LAGUNA DE ANTALA/image.jpg	static/municipalitie/SILOS/places/LAGUNA DE ANTALA/background.jpg
46	13	LAGUNA DE JAIMES	LAGUNA DE JAIMES Ubicada en Santo Domingo de Silos, La hermosa Laguna de Jaimes, es uno de los Lugares más increíbles y poco conocidos del Departamento, Y es una gran aventura, que tienen que vivir.\n\nPrimero se Debe llegar a Berlin Santander que queda a unas aproximadamente 3 horas y media de Cúcuta, y luego tomar un desvio a Mano Izquierda, donde se encuentra la estación de policia del pueblo, y ahi seguir por un camino destapado de 1 horas y 20 minutos aproximadamente.\n\nLuego llegarás a La Vereda de Antala, Y Preguntar por don José, quienes el el dueño de la finca, a la cual se puede ingresar. Importante es que el vehiculo entra hasta la laguna.\n\nDurante el Camino destapado, verás uno de los paisajes más increíbles y maravillosos de Norte de Santander y de Colombia, La verdad quedas maravillado de tanta inmensidad y de lo hermoso que es. La entrada tiene un Costo de $5.000 donde se le paga al Señor Don José, pero vale muchísimo la pena, visitar y conocer esta maravilla natural\n\nImportante Siempre cuando visiten estos lugares vayan con guias locales, ya quienes conocen de antemano por completo los lugares y son a quienes les dan el permiso de ingreso, SIempre Viajo con Mi guia especializada\n	static/municipalitie/SILOS/places/LAGUNA DE JAIMES/video.mp4	static/municipalitie/SILOS/places/LAGUNA DE JAIMES/image.jpg	static/municipalitie/SILOS/places/LAGUNA DE JAIMES/background.jpg
47	13	LAGUNA TAMANÁ	 Esta vez nos fuimos a,descubrir y conocer, una de las Lagunas más Hermosas de Nuestro Departamento, donde les adelanto, es vivir una GRAN AVENTURA y te encontraras con la HERMOSA LAGUNA TAMANÁ.\n\nLa LAGUNA TAMANÁ, esta ubicada en el Municipio de Santo Domingo de Silos, en el complejo Lagunar Antala en Berlin, a aproximadamente 4 Horas de Cúcuta hasta Berlin, Con una Altura de 3.850 MSNM, donde hace muchisimo frio y se disfruta el clima hasta mas no poder.\n\nPara Llegar a la Laguna, se Debe llegar a Berlin y Voltear a Mano izquierda, por el Puesto de Policia de Berlin, hacia el Complejo Laguna Antala, Y por el camino te va llevando hacia ella, El Camino es destapado (trocha) que dura aproximadamente 2 horas, donde viviras una gran aventura, y contemplaras paisajes inigualables. (el camino es duro, pasas por barro, pasto mojado y tieene descensos y ascensos empinados)\n \nAl ingresar deberas cancelar $10.000 COP, para acceder a la Laguna y Después se Comienza una caminata montaña arriba de aproximadamente 1 hora, donde la montaña es tu amiga y te rodeara del clima del paramo y de nuestros amigos los frailejones.\n	static/municipalitie/SILOS/places/LAGUNA TAMANÁ/video.mp4	static/municipalitie/SILOS/places/LAGUNA TAMANÁ/image.jpg	static/municipalitie/SILOS/places/LAGUNA TAMANÁ/background.jpg
48	13	MIRADOR DEL CONDOR	El hermoso mirador del cóndor ubicado en el sector el Alto de la vereda saldo Chiquito del municipio de Silos.\n\nUna de las características más importantes del cóndor andino es su monogamia. Elige una pareja para toda la vida; de ahí que, se le llame “amor eterno”. Como eterno es su amor con el municipio de Silos. Aquí hace presencia, volando a alturas que superan los tres mil metros sobre el nivel del mar. A esas alturas ponen sus huevos las hembras que son más escasas que los machos, de ahí la preocupación por la poca reproducción. Ponen un huevo cada dos o tres años.\n\nComo es bien sabido, esta ave exótica de nuestra región se encuentra en vía de extinción, a nivel crítico en Colombia. De ahí que se propenda por su cuidado y protección.\n\nEl Cóndor, ave representativa del Páramo de San Turban, del cual nuestro municipio de Silos hace parte en un 65% de territorio. Lo encontramos en la Ruta “El Paso de Ambrosio Alfinger”, en los sectores de Antalá y Entrada del agua. Fue precisamente por allí, por donde ingresó a nuestro territorio al alemán, Ambrosio Alfinger, fundador de Silos en el año 1531. \n\nEsas casualidades que engrandecen la trascendencia de este símbolo Nacional. Por eso, nos sentimos orgullosos de que se haya construido la colosal imagen de esta majestuosa ave en nuestro pueblo.\n\nLa vista del Cóndor tenía que estar hacia la Laguna del Cornal, riqueza hídrica y paramuna de la cordillera oriental y hacia el Páramo de Santurbán, donde en repetidas oportunidades ha hecho presencia, como guardián que vigila sigilosamente para que la mano del hombre no siga arrasando con la naturaleza, donde El Cóndor Andino es símbolo de grandeza y libertad.\n	static/municipalitie/SILOS/places/MIRADOR DEL CONDOR/video.mp4	static/municipalitie/SILOS/places/MIRADOR DEL CONDOR/image.jpg	static/municipalitie/SILOS/places/MIRADOR DEL CONDOR/background.jpg
49	14	ENCANTO DE CAFÉ	Encanto Café, tambien conocido como la Herencia Hospedaje y Café Es un nuevo hospedaje campestre con cabañas que esta dando de que Hablar en el Municipio de Toledo, es el lugar perfecto para parchar un fin  de semana Con sus amigos, Tambien para que sorprenda a su pareja Disfrutando de la naturaleza y de los paisajes increibles\n\nSi quieren venir a pasar la noche, hay  cabañas con habitaciones familiares de 4 a 6 personas que tiene un costo entre semana de $40.000 por persona Con desayuno incluido y $50.000 los fines de semana tambien por persona Si quieres mas comodidad y conexion con la naturaleza, puedes disfrutar\n\ncon su pareja de sus glamping, que tiene un costo de $120.000 entre y de $180.000 los fines de semana, con desayuno y bebida de Bienvenida\n\nSi eres amante del cafe, y del turismo cafetero. Este concepto es increible la cabaña cuenta con cocina para que se ahorren unos pesitos, y zona BBQ tambien en la noche se iumina y se ve realmente hermosa les recomiendo que vengan para que tengan esta vista privilegiada \n	static/municipalitie/TOLEDO/places/ENCANTO DE CAFÉ/video.mp4	static/municipalitie/TOLEDO/places/ENCANTO DE CAFÉ/image.jpg	static/municipalitie/TOLEDO/places/ENCANTO DE CAFÉ/background.jpg
50	14	TOBOGAN NATURAL	Tobogán natural Las Lajas, Toledo Norte de Santander Territorio Mágico..!!\n\nEl municipio de Toledo, ubicado en el Norte de Santander, alberga uno de los espectáculos naturales más divertidos de Colombia: el tobogán Las Lajas.\n\nSe trata de un tobogán natural, formado por la corteza de roca que tiene el fondo del riachuelo Las Lajas que, sumado a la superficie resbaladiza, lo hacen todo un espectáculo natural.\n\nEn este tobogán natural, las personas pueden deslizarse y divertirse en familia sin peligro alguno, además de gozar de un hermoso paisaje.\n\nToledo es uno de los grandes atractivos turísticos en el Norte de Santander y su clima y belleza natural lo hacen un destino muy apetecido para el turismo.	static/municipalitie/TOLEDO/places/TOBOGAN NATURAL/video.mp4	static/municipalitie/TOLEDO/places/TOBOGAN NATURAL/image.jpg	static/municipalitie/TOLEDO/places/TOBOGAN NATURAL/background.jpg
\.


--
-- TOC entry 4824 (class 0 OID 0)
-- Dependencies: 217
-- Name: messages_contacts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cucutoche
--

SELECT pg_catalog.setval('public.messages_contacts_id_seq', 46, true);


--
-- TOC entry 4825 (class 0 OID 0)
-- Dependencies: 219
-- Name: municipalities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cucutoche
--

SELECT pg_catalog.setval('public.municipalities_id_seq', 616, true);


--
-- TOC entry 4826 (class 0 OID 0)
-- Dependencies: 221
-- Name: places_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cucutoche
--

SELECT pg_catalog.setval('public.places_id_seq', 2150, true);


--
-- TOC entry 4655 (class 2606 OID 16638)
-- Name: messages_contacts messages_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.messages_contacts
    ADD CONSTRAINT messages_contacts_pkey PRIMARY KEY (id);


--
-- TOC entry 4657 (class 2606 OID 16709)
-- Name: municipalities municipalities_name_key; Type: CONSTRAINT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.municipalities
    ADD CONSTRAINT municipalities_name_key UNIQUE (name);


--
-- TOC entry 4659 (class 2606 OID 16707)
-- Name: municipalities municipalities_pkey; Type: CONSTRAINT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.municipalities
    ADD CONSTRAINT municipalities_pkey PRIMARY KEY (id);


--
-- TOC entry 4661 (class 2606 OID 16721)
-- Name: places places_municipality_id_name_key; Type: CONSTRAINT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_municipality_id_name_key UNIQUE (municipality_id, name);


--
-- TOC entry 4663 (class 2606 OID 16719)
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);


--
-- TOC entry 4664 (class 2606 OID 16722)
-- Name: places places_municipality_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cucutoche
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_municipality_id_fkey FOREIGN KEY (municipality_id) REFERENCES public.municipalities(id) ON DELETE CASCADE;


-- Completed on 2025-06-19 14:12:25

--
-- PostgreSQL database dump complete
--

